### ISSUE TITLE
Dependencies seem to be missing

### ISSUE THREAD

**Issue by shamanorris** [lahsivjar/spring-websocket-template#19]
I copied the files manually from withSocket directory, and added the parent pom dependencies in the same pom. But when I update maven in IntelliJ there are still missing dependencies in Application.java and WebConfig.java.
IDE suggested the following dependencies to be added. It seems to get it fixed:

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <version>1.5.9.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <version>4.3.13.RELEASE</version>
        </dependency>

**Comment by lahsivjar** [comment]
@shamanorris Both these dependencies should be transitively imported. Try this as the pom if you want to launch it independently. Let me know if it works: https://gist.github.com/lahsivjar/2c0b8073fb29f6c9abbc8a8f27842fe9

**Comment by shamanorris** [comment]
@lahsivjar I recreated the project in a different folder and port to test your pom. It worked with no need of any modifications! I'll use your version now, thanks!
